# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  username,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/0b7de90c-38a7-41d8-aa6a-8d7901f19bd8";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "ssd"
      "compress=zstd"
      "noatime"
      "space_cache=v2"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/0b7de90c-38a7-41d8-aa6a-8d7901f19bd8";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "ssd"
      "compress=zstd"
      "noatime"
      "space_cache=v2"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/0b7de90c-38a7-41d8-aa6a-8d7901f19bd8";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "ssd"
      "compress=zstd"
      "noatime"
      "space_cache=v2"
    ];
  };

  fileSystems."/.snapshots" = {
    device = "/dev/disk/by-uuid/0b7de90c-38a7-41d8-aa6a-8d7901f19bd8";
    fsType = "btrfs";
    options = [
      "subvol=@snapshots"
      "ssd"
      "compress=zstd"
      "noatime"
      "space_cache=v2"
    ];
  };

  fileSystems."/home/.snapshots" = {
    device = "/dev/disk/by-uuid/0b7de90c-38a7-41d8-aa6a-8d7901f19bd8";
    fsType = "btrfs";
    options = [
      "subvol=@home-snapshots"
      "ssd"
      "compress=zstd"
      "noatime"
      "space_cache=v2"
    ];
  };

  fileSystems."/home/${username}/vmware" = {
    device = "/dev/disk/by-uuid/0b7de90c-38a7-41d8-aa6a-8d7901f19bd8";
    fsType = "btrfs";
    options = [
      "subvol=@vmware"
      "ssd"
      "compress=zstd"
      "noatime"
      "space_cache=v2"
    ];
  };

  fileSystems."/mnt/ssd1" = {
    device = "/dev/disk/by-uuid/37af0ef2-f5c8-437f-8e9b-545a069f925a";
    fsType = "ext4";
    options = ["defaults" "nofail"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6601-E8FF";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
